name: "Build"

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: write

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        triplet: [x64-windows]
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2 # https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Run pip"
        run: python -m pip install -r requirements.txt

      - name: "Run chocolatey"
        run: |
          choco install --yes pkgconfiglite

      - uses: lukka/get-cmake@v3.31.4
      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "C:/vcpkg" # VCPKG_INSTALLATION_ROOT
          vcpkgGitCommitId: "6f29f12e82a8293156836ad81cc9bf5af41fe836" # 2025.01.13
          vcpkgJsonGlob: '**/vcpkg.json'
          vcpkgConfigurationJsonGlob: '**/vcpkg-configuration.json'
          runVcpkgInstall: true
          runVcpkgFormatString: '[`install`, `--clean-buildtrees-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALL_DIR]`]'
        env:
          VCPKG_INSTALL_DIR: "${{ github.workspace }}/externals"
          VCPKG_TARGET_TRIPLET: "${{ matrix.triplet }}"

      - name: "Run meson(setup, ${{ matrix.triplet }})"
        id: meson-setup
        run: |
          meson setup --backend vs2022 --vsenv `
            --cross-file "meson-${{ matrix.triplet }}.ini" `
            --buildtype debug `
            "builddir"

      - name: "Run meson(build/install)"
        run: |
          meson compile -C "builddir"
          meson install -C "builddir"

      - uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: meson-logs-windows
          path: builddir/meson-logs/
          retention-days: 1

  windows_sample_x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '6.x'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Run pip"
        run: python -m pip install -r requirements.txt

      - name: "Run chocolatey"
        run: |
          choco install --yes pkgconfiglite

      - uses: lukka/get-cmake@v3.31.4
      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "C:/vcpkg" # VCPKG_INSTALLATION_ROOT
          vcpkgGitCommitId: "6f29f12e82a8293156836ad81cc9bf5af41fe836" # 2025.01.13
          vcpkgJsonGlob: '**/vcpkg.json'
          vcpkgConfigurationJsonGlob: '**/vcpkg-configuration.json'
          runVcpkgInstall: true
          runVcpkgFormatString: '[`install`, `--clean-buildtrees-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALL_DIR]`]'
        env:
          VCPKG_INSTALL_DIR: "${{ github.workspace }}/externals"
          VCPKG_TARGET_TRIPLET: "x64-windows"

      - name: "Run vcpkg integrate"
        run: vcpkg integrate install

      - name: "Run meson(debug)"
        run: |
          meson setup --backend vs2022 --vsenv `
            --cross-file "meson-x64-windows.ini" `
            --prefix "${{ github.workspace }}/externals/x64-windows/debug" `
            --buildtype debug `
            "build-dbg"
          meson compile -C "build-dbg"
          meson install -C "build-dbg"

      - name: "Run meson(release)"
        run: |
          meson setup --backend vs2022 --vsenv `
            --cross-file "meson-x64-windows.ini" `
            --prefix "${{ github.workspace }}/externals/x64-windows" `
            "build-rel"
          meson compile -C "build-rel"
          meson install -C "build-rel"

      - name: "Run nuget restore"
        run: |
          nuget restore sample.sln
          nuget restore sample.vcxproj -SolutionDirectory .
        working-directory: sample

      - name: "Run MSBuild(x64, Debug)"
        run: |
          MSBuild sample.sln `
            /p:Platform=x64 `
            /p:AppxBundlePlatforms=x64 `
            /p:Configuration=Debug `
            /p:AppxPackageDir="${{ github.workspace }}/outputs" `
            /p:GenerateAppxPackageOnBuild=false
        working-directory: sample

      - name: "Run MSBuild(x64, Release)"
        run: |
          MSBuild sample.sln `
            /p:Platform=x64 `
            /p:AppxBundlePlatforms=x64 `
            /p:Configuration=Release `
            /p:AppxPackageDir="${{ github.workspace }}/outputs" `
            /p:GenerateAppxPackageOnBuild=false
        working-directory: sample

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        triplet: [arm64-osx]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Run pip"
        run: python -m pip install -r requirements.txt

      - uses: lukka/get-cmake@v3.31.4
      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "/Users/Shared/vcpkg"
          vcpkgJsonGlob: '**/vcpkg.json'
          vcpkgConfigurationJsonGlob: '**/vcpkg-configuration.json'
          runVcpkgInstall: true
          runVcpkgFormatString: '[`install`, `--clean-buildtrees-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALL_DIR]`]'
        env:
          VCPKG_INSTALL_DIR: "${{ github.workspace }}/externals"
          VCPKG_TARGET_TRIPLET: "${{ matrix.triplet }}"

      - name: "Run meson(setup, ${{ matrix.triplet }})"
        id: meson-setup
        run: |
          meson setup --backend xcode \
            --cross-file "meson-${{ matrix.triplet }}.ini" \
            "builddir"

      - name: "Run meson(build/install)"
        run: |
          meson compile -C "builddir"
          # meson install -C "builddir"

      - uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: meson-logs-macos
          path: builddir/meson-logs/
          retention-days: 1
